### ISSUE TITLE
显示文章标题

### ISSUE THREAD

**Issue by cmmei** [Info-cn/Terminus#2]
想要显示文章标题，不知道这样修改对不对：[branch: iss01](https://github.com/Info-cn/Terminus/commit/05c46ee1ec0116e8aa0b7679a1ad622ac9319bad)

**Comment by tsai1993** [comment]
你可以搭建一个本地 jkelly serve 预览，https://jekyllrb.com/docs/installation/。
没明白你想干啥，难道没有文章标题么？

**Comment by cmmei** [comment]
浏览器打开或是微信里分享 端点星的文章，不会显示具体文章标题，始终显示「端点星」。

**Comment by tsai1993** [comment]
如果分享到朋友圈，只能直接贴链接，因为没备案，直接分享别人是看不到的。

你说的是什么情况，我还没搞明白，可以给我微信截图看一下。

**Comment by cmmei** [comment]
像上图这样，不显示文章标题，默认显示 端点星 三个字。

**Comment by tsai1993** [comment]
你先确认一下别人能不能看到，之后我再了解一下微信的分享机制。https://www.zhihu.com/question/47562376

你发一条，仅对我可见就好了。

**Comment by cmmei** [comment]
刚发了一条，仅 你 可见。

**Comment by tsai1993** [comment]
ok了

**Comment by cmmei** [comment]
Thanks ~
